version: '3.8'

services:

  backend:
    build:
      context: .
    ports:
      - "3010:3010"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      BACKEND_API_URL: http://backend:3010/api

networks:
  app_network:
    driver: bridge